"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState, useTransition } from "react";
import { ArrowLeft, LoaderCircle, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { deleteProgressActivityAction, saveProgressActivityAction } from "@/actions/projects";
import MaterialApprovalsPageClient from "@/features/material-approvals/components/MaterialApprovalsPageClient";
import PurchasingApprovalsPageClient from "@/features/purchasing-approvals/components/PurchasingApprovalsPageClient";
import type { ProjectRecord } from "../types";

type Activity = { id: string; activity: string; weight_percent: number; progress_percent: number };
type Estimate = { id: string; status: string; estimate_total: number; updated_at: string };
type BudgetItem = { id: string; name: string; category: string; estimated_cost: number; actual_spent: number; status: string };
const TABS = ["overview", "budget", "materials", "purchasing", "estimates"] as const;

export default function ProjectWorkspaceClient({ project, role, activities, estimates, budgetItems }: { project: ProjectRecord; role: "ceo" | "engineer"; activities: Activity[]; estimates: Estimate[]; budgetItems: BudgetItem[] }) {
  const router = useRouter(); const params = useSearchParams(); const selected = params.get("tab");
  const tab = TABS.includes(selected as any) ? selected! : "overview"; const [pending, startTransition] = useTransition();
  const estimated = budgetItems.reduce((sum, item) => sum + Number(item.estimated_cost), 0); const spent = budgetItems.reduce((sum, item) => sum + Number(item.actual_spent), 0);
  const money = (value: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 0 }).format(value);
  function addActivity(data: FormData) { startTransition(async () => { try { await saveProgressActivityAction({ projectId: project.id, activity: String(data.get("activity") || ""), weightPercent: Number(data.get("weight")), progressPercent: Number(data.get("progress")) }); toast.success("Progress activity saved."); router.refresh(); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to save progress."); } }); }
  function removeActivity(id: string) { startTransition(async () => { try { await deleteProgressActivityAction(id, project.id); router.refresh(); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to delete activity."); } }); }
  return <div className="space-y-5">
    <header className="rounded-2xl border border-slate-200 bg-white p-5"><Link href="/projects" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-800"><ArrowLeft size={15}/>Project portfolio</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Project workspace</p><h1 className="text-2xl font-bold text-slate-950">{project.name}</h1><p className="text-sm text-slate-500">{project.location} · {project.engineer}</p></div><div className="text-right"><p className="text-xs uppercase text-slate-500">Budget ceiling</p><p className="text-xl font-bold">{money(project.budget)}</p></div></div></header>
    <nav className="flex gap-2 overflow-x-auto border-b pb-3">{TABS.map((item) => <Link key={item} href={`/projects/${project.id}?tab=${item}`} className={`rounded-xl px-4 py-2 text-sm font-semibold capitalize ${tab === item ? "bg-emerald-800 text-white" : "border bg-white text-slate-600"}`}>{item}</Link>)}</nav>
    {tab === "overview" ? <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><Card label="Completion" value={`${project.progress}%`}/><Card label="Activities" value={String(activities.length)}/><Card label="Remaining budget" value={money(project.budget - spent)}/></div><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Engineering progress</h2>{role === "engineer" ? <form action={addActivity} className="mt-4 grid gap-3 sm:grid-cols-4"><input name="activity" required placeholder="Activity" className="h-10 rounded-lg border px-3 sm:col-span-2"/><input name="weight" required type="number" min="0.01" max="100" step="0.01" placeholder="Weight %" className="h-10 rounded-lg border px-3"/><input name="progress" required type="number" min="0" max="100" step="0.01" placeholder="Progress %" className="h-10 rounded-lg border px-3"/><button disabled={pending} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-emerald-800 text-white sm:col-span-4">{pending ? <LoaderCircle size={15} className="animate-spin"/> : <Plus size={15}/>}Add activity</button></form> : null}<div className="mt-4 divide-y">{activities.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-semibold">{item.activity}</p><p className="text-xs text-slate-500">Weight {item.weight_percent}% · Progress {item.progress_percent}%</p></div>{role === "engineer" ? <button disabled={pending} onClick={() => removeActivity(item.id)} className="text-rose-600" aria-label="Delete activity"><Trash2 size={16}/></button> : null}</div>)}{activities.length === 0 ? <p className="py-6 text-sm text-slate-500">No progress activities yet.</p> : null}</div></section></div> : null}
    {tab === "budget" ? <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><Card label="Budget ceiling" value={money(project.budget)}/><Card label="Estimated" value={money(estimated)}/><Card label="Actual spent" value={money(spent)}/></div><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Budget items</h2>{budgetItems.map((item) => <div key={item.id} className="mt-3 flex justify-between border-t pt-3 text-sm"><span>{item.name} <small className="text-slate-500">({item.category})</small></span><span>{money(item.actual_spent)} / {money(item.estimated_cost)}</span></div>)}{!budgetItems.length ? <p className="mt-4 text-sm text-slate-500">No budget items yet. Add costs from the Budget Tracker.</p> : null}<Link href={`/projects?section=budget-tracker`} className="mt-4 inline-flex text-sm font-semibold text-emerald-800">Open full Budget Tracker</Link></section></div> : null}
    {tab === "materials" ? <><PreviewNotice label="Material approvals are preview data in this phase."/><MaterialApprovalsPageClient projectName={project.name}/></> : null}
    {tab === "purchasing" ? <><PreviewNotice label="Purchasing approvals are preview data in this phase."/><PurchasingApprovalsPageClient projectName={project.name}/></> : null}
    {tab === "estimates" ? <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Project estimates</h2>{estimates.map((item) => <div key={item.id} className="mt-3 flex justify-between border-t pt-3"><span className="capitalize">{item.status}</span><span className={Number(item.estimate_total) > project.budget ? "font-bold text-rose-600" : "font-semibold text-emerald-700"}>{money(item.estimate_total)}{Number(item.estimate_total) > project.budget ? " · Over ceiling" : ""}</span></div>)}{!estimates.length ? <p className="mt-4 text-sm text-slate-500">No estimates linked to this project.</p> : null}</section> : null}
  </div>;
}
function Card({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border bg-white p-5"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>; }
function PreviewNotice({ label }: { label: string }) { return <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">{label} Changes here are not stored in Supabase yet.</div>; }
