import type { ProjectRecord } from "../types";

export const MOCK_PROJECTS: ProjectRecord[] = [
  {
    id: "proj-1",
    name: "Grand Horizon Towers",
    location: "Sgt. Esguerra Ave, Quezon City",
    client: "Horizon Land Dev Corp",
    status: "active",
    budget: 45000000,
    spent: 18500000,
    progress: 42,
    startDate: "2026-01-10",
    endDate: "2027-06-30",
    manager: "Engr. Richard Gomez",
    engineer: "Engineer User", // Matches current role user
    tasksCount: 15,
    completedTasksCount: 6,
    materialsCount: 28,
    description: "A 22-story residential condominium with high-end amenities and green building design certifications.",
  },
  {
    id: "proj-2",
    name: "Vista Verde Residences",
    location: "Amang Rodriguez, Pasig City",
    client: "Verde Living Inc",
    status: "active",
    budget: 28000000,
    spent: 14200000,
    progress: 55,
    startDate: "2026-02-15",
    endDate: "2026-12-15",
    manager: "Engr. Sarah Lee",
    engineer: "Engineer User",
    tasksCount: 12,
    completedTasksCount: 7,
    materialsCount: 19,
    description: "Medium-rise residential apartment project focusing on affordable smart-home structures.",
  },
  {
    id: "proj-3",
    name: "Skyline Business Park",
    location: "C-5 Road, Taguig City",
    client: "Skyline Properties",
    status: "active",
    budget: 95000000,
    spent: 24000000,
    progress: 25,
    startDate: "2026-04-01",
    endDate: "2027-12-31",
    manager: "Engr. Richard Gomez",
    engineer: "Engineer User",
    tasksCount: 22,
    completedTasksCount: 4,
    materialsCount: 45,
    description: "Modern commercial complex designed with structural glass facade panels and energy-efficient systems.",
  },
  {
    id: "proj-4",
    name: "Novaliches Warehouse Complex",
    location: "Quirino Highway, Novaliches",
    client: "FastLogix Logistics",
    status: "on_hold",
    budget: 18000000,
    spent: 16500000,
    progress: 90,
    startDate: "2025-08-01",
    endDate: "2026-05-15",
    manager: "Engr. Sarah Lee",
    engineer: "Engineer User",
    tasksCount: 10,
    completedTasksCount: 9,
    materialsCount: 12,
    description: "A industrial warehouse hub. Currently on hold waiting for client's electrical connection permissions.",
  },
  {
    id: "proj-5",
    name: "Cebu IT Hub Expansion",
    location: "Lahug, Cebu City",
    client: "Visayas Tech Park",
    status: "planning",
    budget: 120000000,
    spent: 0,
    progress: 0,
    startDate: "2026-09-01",
    endDate: "2028-03-30",
    manager: "Engr. Richard Gomez",
    engineer: "Engr. Mark Santos",
    tasksCount: 8,
    completedTasksCount: 0,
    materialsCount: 0,
    description: "New office tower with 10 BPO-ready floors, complete back-up generators, and triple-redundant data hubs.",
  },
];
