import type { TaskRecord } from "../types";

export const MOCK_TASKS: TaskRecord[] = [
  {
    id: "task-1",
    title: "Foundation Rebar Quality Check",
    description: "Inspect the layout and steel rebar specifications of grid A-1 to C-4 before concrete pouring.",
    projectName: "Grand Horizon Towers",
    dueDate: "2026-07-20",
    priority: "high",
    status: "in_progress",
    progress: 60,
    notes: "Partially inspected, waiting for spacing corrections on grid B-2.",
  },
  {
    id: "task-2",
    title: "Electrical Conduit Rough-Ins",
    description: "Install conduit pipes for the 2nd-floor ceiling lighting and socket layouts.",
    projectName: "Grand Horizon Towers",
    dueDate: "2026-07-22",
    priority: "medium",
    status: "todo",
    progress: 0,
  },
  {
    id: "task-3",
    title: "Structural Columns Concrete Pouring",
    description: "Supervise concrete pouring of 1st-floor columns C5 to C12. Ensure compression test cylinders are taken.",
    projectName: "Vista Verde Residences",
    dueDate: "2026-07-19",
    priority: "high",
    status: "in_progress",
    progress: 40,
    notes: "Transit mixers delayed by 30 mins due to traffic.",
  },
  {
    id: "task-4",
    title: "Plumbing Deck Sleeves Installation",
    description: "Align plumbing sleeve positions according to isometric drawings prior to structural slab casting.",
    projectName: "Vista Verde Residences",
    dueDate: "2026-07-18",
    priority: "medium",
    status: "completed",
    progress: 100,
    notes: "All sleeves verified and tied down securely.",
  },
  {
    id: "task-5",
    title: "Material Submittal Review: Wall Tiles",
    description: "Check physical tile samples submitted by vendor for bathroom wet areas against architectural specs.",
    projectName: "Skyline Business Park",
    dueDate: "2026-07-15",
    priority: "low",
    status: "completed",
    progress: 100,
    notes: "Approved sample #A2 for installation.",
  },
  {
    id: "task-6",
    title: "Excavation and Shoring Verification",
    description: "Verify depth of basement excavation and inspect safety shoring structure integrity.",
    projectName: "Skyline Business Park",
    dueDate: "2026-07-25",
    priority: "high",
    status: "todo",
    progress: 0,
  },
  {
    id: "task-7",
    title: "Boundary Fence Brickwork Layout",
    description: "Establish baseline offsets for boundary fence alignment and lay down first three courses.",
    projectName: "Novaliches Warehouse Complex",
    dueDate: "2026-07-14",
    priority: "low",
    status: "delayed",
    progress: 15,
    notes: "Delayed due to heavy rainfall and muddy terrain. Waiting for site dry out.",
  },
];
